url: "https://beta.digitathya.com/accessCheck"

browser: "chrome"
access_code: "2560"

users:
  superadmin:
    username: "loadtesting_superadmin@mailinator.com"
    password: "Newuser@123"

  manufacturer:
    username: "manufacturer@test.com"
    password: "Password123"

implicit_wait: 10
headless: false    # set true in CI if you want headless
