url: "https://beta.digitathya.com/admin/login"
browser: "chrome"

users:
  superadmin:
    username: "superadmin@test.com"
    password: "Password123"

  manufacturer:
    username: "manufacturer@test.com"
    password: "Password123"

implicit_wait: 10
headless: false    # set true in CI if you want headless
