url: "https://beta.digitathya.com/admin/login"
browser: "chrome"
access_code: "2560"   # replace with your real code

users:
  superadmin:
    username: "yivake3549@gusronk.com"
    password: "Newuser@123"

  manufacturer:
    username: "manufacturer@test.com"
    password: "Password123"

implicit_wait: 10
explicit_wait: 10          # <-- NEW (for WebDriverWait)
headless: false

# Only required for ULAA
ulaa_path: "C:/Program Files/Zoho/Ulaa/Application/ulaa.exe"
